services:
  qa-mesto:
    build: .
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      - HEADLESS=true
      - ENV=${TARGET_ENV:-dev}
      - BROWSER=${BROWSER:-chromium}
      - TEST_TYPE=${TEST_TYPE:-}
      - TEST_FILES=${TEST_FILES:-}
    command: >
      sh -c "pytest -v $TEST_FILES --env=${ENV:-dev} --browser=${BROWSER:-chromium} --alluredir=/app/allure-results ${TEST_TYPE:+-m \"$TEST_TYPE\"}"