services:
  qa-mesto:
    build: .
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      - HEADLESS=true
      - ENV=${TARGET_ENV}
      - BROWSER=${BROWSER}
      - TEST_TYPE=${TEST_TYPE}
      - TEST_FILES=${TEST_FILES}
    command: >
      sh -c "if [ \"$TEST_TYPE\" = \"all\" ]; then
               pytest -v $TEST_FILES --alluredir=/app/allure-results;
             else
               pytest -v -m \"$TEST_TYPE\" $TEST_FILES --alluredir=/app/allure-results;
             fi"
