[pytest]
# --- Основные опции запуска ---
# -s: показывать print() в консоли, -v: подробный вывод
# -n auto: распараллеливать тесты (нужен pytest-xdist), значительно ускоряет прогон
addopts = -sv -n auto --alluredir=allure-results --browser chromium --headed

# --- Опции для pytest-playwright ---
# --browser chrome: браузер по умолчанию
# --headed: запускать браузер в видимом режиме (уберите для запусков в CI/CD)
# --base-url: базовый URL вашего приложения, очень удобно для тестов


# --- Пути и маркеры ---
testpaths = tests
markers =
    smoke: smoke tests
    regression: regression tests
